package com.mercuryred.render.interfaces.uiplus;

import com.mercuryred.render.interfaces.ui.Font;
import com.mercuryred.render.interfaces.ui.MenuComponent;
import com.mercuryred.render.interfaces.ui.PopupMenu;
import com.mercuryred.render.interfaces.ui.event.MouseListener;
import com.mercuryred.render.interfaces.ui.LayoutManager;
import com.mercuryred.render.interfaces.ui.event.ComponentListener;
import com.mercuryred.render.interfaces.ui.Container;
import com.mercuryred.render.interfaces.uiplus.plaf.ComponentUI;
import com.mercuryred.render.interfaces.ui.Color;
import com.mercuryred.render.interfaces.uiplus.Icon;
import com.mercuryred.render.interfaces.uiplus.border.Border;
import com.mercuryred.render.interfaces.ui.Component;
import com.mercuryred.render.interfaces.ui.event.ContainerListener;
import com.mercuryred.render.interfaces.ui.Rectangle;
import com.mercuryred.render.interfaces.ui.event.MouseMotionListener;
import com.mercuryred.render.interfaces.uiplus.plaf.TabbedPaneUI;
import com.mercuryred.render.interfaces.ui.event.FocusListener;
import com.mercuryred.render.interfaces.ui.Dimension;
import com.mercuryred.render.interfaces.ui.event.FocusEvent;
import com.mercuryred.render.interfaces.ui.Insets;
import com.mercuryred.render.interfaces.uiplus.event.ChangeListener;
import com.mercuryred.render.interfaces.ui.Point;

import java.beans.PropertyChangeListener;


public interface JTabbedPane {

    TabbedPaneUI getUI();
    // ComponentUI getUI();
    void addChangeListener(ChangeListener l);
    void removeChangeListener(ChangeListener l);
    int getTabPlacement();
    int getTabLayoutPolicy();
    int getSelectedIndex();
    void setSelectedIndex(int index);
    Component add(Component component);
    Component add(String title, Component component);
    Component add(Component component, int index);
    void add(Component component, Object constraints);
    void add(Component component, Object constraints, int index);
    void remove(Component component);
    void remove(int index);
    int getTabCount();
    String getTitleAt(int index);
    Icon getIconAt(int index);
    Icon getDisabledIconAt(int index);
    Color getBackgroundAt(int index);
    Color getForegroundAt(int index);
    boolean isEnabledAt(int index);
    Component getComponentAt(int index);
    int getMnemonicAt(int tabIndex);
    int getDisplayedMnemonicIndexAt(int tabIndex);
    void setTabComponentAt(int index, Component component);
    Component getTabComponentAt(int index);
    int indexOfTabComponent(Component tabComponent);
    boolean isRequestFocusEnabled();
    void requestFocus();
    boolean requestFocus(boolean temporary);
    void setBorder(Border border);
    Border getBorder();
    Insets getInsets();
    Insets getInsets(Insets insets);
    void setForeground(Color fg);
    void setBackground(Color bg);
    void setFont(Font font);
    void putClientProperty(Object key, Object value);
    Rectangle getBounds(Rectangle rv);
    Dimension getSize(Dimension rv);
    int getWidth();
    int getHeight();
    boolean isOpaque();
    void repaint(long tm, int x, int y, int width, int height);
    void repaint(Rectangle r);
    void revalidate();
    int getComponentCount();
    Component getComponent(int n);
    LayoutManager getLayout();
    void doLayout();
    void addContainerListener(ContainerListener l);
    void removeContainerListener(ContainerListener l);
    Component getComponentAt(int x, int y);
    Component getComponentAt(Point p);
    void addPropertyChangeListener(PropertyChangeListener listener);
    void addPropertyChangeListener(String propertyName, PropertyChangeListener listener);
    Container getParent();
    boolean isEnabled();
    Color getBackground();
    Font getFont();
    Dimension getSize();
    Rectangle getBounds();
    void repaint();
    void repaint(long tm);
    void repaint(int x, int y, int width, int height);
    void addComponentListener(ComponentListener l);
    void removeComponentListener(ComponentListener l);
    void addFocusListener(FocusListener l);
    void removeFocusListener(FocusListener l);
    void addMouseListener(MouseListener l);
    void removeMouseListener(MouseListener l);
    MouseListener[] getMouseListeners();
    void addMouseMotionListener(MouseMotionListener l);
    void removeMouseMotionListener(MouseMotionListener l);
    MouseMotionListener[] getMouseMotionListeners();
    void requestFocus(FocusEvent.Cause cause);
    boolean requestFocus(boolean temporary, FocusEvent.Cause cause);
    boolean hasFocus();
    void add(PopupMenu popup);
    void remove(MenuComponent popup);
    void removePropertyChangeListener(PropertyChangeListener listener);
    void removePropertyChangeListener(String propertyName, PropertyChangeListener listener);
}
